In [1]:
#######
# TASK 1: Import pandas and numpy
######

import pandas as pd
import numpy as np

In [4]:
#######
# TASK 2: Set Numpy's random number generator seed to 101
######

np.random.seed(101) 

In [19]:
#######
# TASK 3: Create a NumPy Matrix of 100 rows by 5 columns consisting of
#         random integers from 1-100. (Keep in mind that the upper
#         limit may be exclusive.)
######

mat = np.random.randint(1,101,500)
mat=mat.reshape(100,5)
print(mat)

[[ 29  22  77  17  77]
 [ 87  56  21  45  31]
 [100  31 100  97  37]
 [ 18  73  29  76  90]
 [ 59  35  41  94  63]
 [ 30  12  38  99  65]
 [ 13  68  97  24  70]
 [ 18  41  83  46   5]
 [ 26  17  20  17  81]
 [ 35  94  87  44  32]
 [ 21  93  46  73  77]
 [ 21  17  51  55  78]
 [ 59  97  24  47  57]
 [ 78  54  28  51  57]
 [ 20  47  85  56  86]
 [ 33  25   2  36   6]
 [ 75  27  43  60  43]
 [ 13  21   8  94  93]
 [ 69  88  60  69  87]
 [ 17  76  78  66  88]
 [ 88  67  92  64  70]
 [ 88  90  56  87  58]
 [ 45  14  48  32  78]
 [ 59  90  38  23  23]
 [ 33  49  70  25  92]
 [  4  59  74  69  85]
 [ 49  95  74  76  48]
 [ 22  31   6  65  82]
 [ 96  90  71  29  70]
 [ 32  65  41  34  18]
 [ 80  56   5  78  52]
 [ 48  85  75  21  81]
 [ 44  97  23  42  54]
 [ 26  25  98  37  54]
 [ 19  25  56  71  83]
 [ 41  55  69  94  39]
 [ 34  69  35  30  52]
 [ 64  31  55  14  25]
 [ 15  18   8  14  25]
 [ 77 100  73   1  97]
 [ 68  68  32   7  35]
 [ 66  73  77  89  38]
 [ 99  58  70  52  60]
 [ 19  14  

In [20]:
#######
# TASK 4: Now use pd.DataFrame() to read in this numpy array as a dataframe.
#         Simple pass in the numpy array into that function to get back a
#         dataframe. Pandas will auto label the columns to 0-4
######

df = pd.DataFrame(mat)

In [22]:
#######
# TASK 5: Using your previously created DataFrame, use [df.columns = [...]]
#         (https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas)
#         to rename the pandas columns to be ['f1','f2','f3','f4','label'].
######
df = pd.DataFrame(data=mat, columns=['f1','f2','f3','f4','label'])
print(df)

     f1  f2   f3  f4  label
0    29  22   77  17     77
1    87  56   21  45     31
2   100  31  100  97     37
3    18  73   29  76     90
4    59  35   41  94     63
..  ...  ..  ...  ..    ...
95   40  46   24  38     41
96   11  12   85  24      7
97   25  19   38  25     81
98   25  26    6  68     99
99   79  31   37  53     17

[100 rows x 5 columns]


In [24]:
#######
# TASK 6: Alright, all the other tasks were hopefully straightforward.
#         This final task will allow you to quickly check to see if you are at
#         the right level with pandas! Do the following:
#         Create a dataframe with the columns ['A','B','C','D'] with each column
#         having 50 rows of random numbers for data. The random numbers should be
#         between 0 and 100. (Hint: Use numpy to create the numbers, then pass
#         it in to pd.DataFrame(), check out the data= and index= parameters
#         for that call.)

mat = np.random.randint(1,101,50*4)
mat=mat.reshape(50,4)
df = pd.DataFrame(data=mat, columns=['A','B','C','D'])

print(df)

     A   B   C   D
0    7  25  32  10
1   32  13  49  76
2   26  86  63  22
3   78  69  20  67
4   71  74  50  28
5   36  34  43  34
6   94  40  65   2
7   59  18  60  72
8    2  24  81  27
9   38  35   4  78
10  21   1  63  30
11  48  49  90  50
12  18  87  48  50
13  64  32  36  57
14  84  72  73  12
15  27   3  17   1
16  51   9  80   2
17   2  43  29  91
18  36  86  24  65
19  21  22  44  38
20  90  33  67   3
21   3   1  91  91
22  57  71  54  39
23  90  31  21  21
24  47  21  10   8
25  67  18  66  70
26   8  46  19  74
27  30  70  92  53
28  92  57  50  50
29  43  15  22  16
30  34  60  11  33
31  90  53  29  47
32  10  99  72  81
33  90  83  82   9
34   8  54  65  90
35  24  89  19  84
36  68   8  58  82
37  95  90  96  73
38  81  56  56  79
39  88  75  71  84
40  90  79  66  15
41  37  17  98  47
42   3  18  24  36
43  82  26  19  70
44  22  28  64  57
45  21  95  55  85
46  68  42  66  40
47  80  56  34   7
48   5  11   8  41
49  28   7  89  78
